### ISSUE TITLE
Telemark og Vestfold → Vestfold og Telemark

### ISSUE THREAD

**Issue by arve0** [kyrrelm/kommune-og-regionreform#5]
https://github.com/kyrrelm/kommune-og-regionreform/blob/master/kommune_og_regionsreform_2017_2020.json#L826

Kilder: 
https://kartverket.no/kommunereform/tekniske-endringer/kommune--og-regionsendringer-2020/
https://www.regjeringen.no/no/tema/kommuner-og-regioner/regionreform/regionreform/nye-fylker/id2548426/

**Comment by kyrrelm** [comment]
Rettet i https://github.com/kyrrelm/kommune-og-regionreform/pull/7
